[package]
name = "cargo-run-bin"
description = "A simple tool to build, cache, and run binaries scoped in Cargo.toml rather than installing globally. This acts similarly to npm run and gomodrun."
version = "0.2.0"
authors = ["Dustin Blackman"]
homepage = "https://github.com/dustinblackman/cargo-run-bin"
repository = "https://github.com/dustinblackman/cargo-run-bin"
readme = "README.md"
keywords = ["dev-experiance", "developer-experiance", "bin", "cache"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
cargo_metadata = "0.13.1"
cargo_toml = "0.9.1"
colored = "2.0.0"
fstrings = "0.2.3"
version_check = "0.9.3"

[dev-dependencies]
cargo-cmd = "0.3.1"
cargo-llvm-cov = "0.1.3"
expectest = "0.12.0"
petname = "1.1.1"
speculate = "0.1.2"

[[bin]]
name = "cargo-bin"
path = "src/main.rs"

[package.metadata.commands]
lint = "cargo fmt -- --check && cargo clippy"
lint-fix = "cargo +nightly clippy --fix --allow-dirty -Z unstable-options && cargo fmt"
test-coverage = "cargo bin cargo-llvm-cov --ignore-filename-regex='_test.rs'"
test-coverage-html = "cargo bin cargo-llvm-cov --open --ignore-filename-regex='_test.rs'"
test-coverage-lcov = '''
  rm -f lcov.info
  cargo bin cargo-llvm-cov --lcov --output-path lcov.info --ignore-filename-regex='_test.rs'
'''
