[package]
name = "cargo-run-bin"
version = "0.4.0"
authors = ["Dustin Blackman"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
edition = "2021"
homepage = "https://github.com/dustinblackman/cargo-run-bin"
keywords = ["dev-experiance", "developer-experiance", "bin", "cache"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/dustinblackman/cargo-run-bin"
description = "A simple tool to build, cache, and run binaries scoped in Cargo.toml rather than installing globally. This acts similarly to npm run and gomodrun."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
cargo_metadata = "0.13.1"
cargo_toml = "0.10.3"
home = "0.5.3"
owo-colors = "3.5.0"
serde = "1.0.149"
toml = "0.5.9"
version_check = "0.9.3"

[dev-dependencies]
expectest = "0.12.0"
petname = "1.1.1"

[[bin]]
name = "cargo-bin"
path = "src/main.rs"

[package.metadata.bin]
cargo-deny = "0.13.5"
cargo-llvm-cov = "0.1.3"
dprint = "0.30.3"

[package.metadata.commands]
lint = '''
cargo +nightly fmt -- --check
cargo clippy
cargo bin dprint check
cargo bin cargo-deny check licenses
'''
lint-fix = '''
cargo clippy --fix --allow-dirty
cargo fix --allow-dirty
cargo +nightly fmt
cargo bin dprint fmt
'''
test-coverage = "cargo bin cargo-llvm-cov --ignore-filename-regex='_test.rs'"
test-coverage-html = "cargo bin cargo-llvm-cov --open --ignore-filename-regex='_test.rs'"
test-coverage-lcov = '''
  rm -f lcov.info
  cargo bin cargo-llvm-cov --lcov --output-path lcov.info --ignore-filename-regex='_test.rs'
'''
