[alias]
android = ["bin", "cargo-android"]
cmd = ["bin", "cargo-cmd"]
deny = ["bin", "cargo-deny"]
llvm-cov = ["bin", "cargo-llvm-cov"]
mobile = ["bin", "cargo-mobile"]
nextest = ["bin", "cargo-nextest"]
