[alias]
binstall = ["bin", "cargo-binstall"]
cmd = ["bin", "cargo-cmd"]
deny = ["bin", "cargo-deny"]
dist = ["bin", "cargo-dist"]
insta = ["bin", "cargo-insta"]
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]
release = ["bin", "cargo-release"]
watch = ["bin", "cargo-watch"]
