[alias]
android = ["bin", "cargo-android"]
binstall = ["bin", "cargo-binstall"]
cmd = ["bin", "cargo-cmd"]
deny = ["bin", "cargo-deny"]
dist = ["bin", "cargo-dist"]
llvm-cov = ["bin", "cargo-llvm-cov"]
mobile = ["bin", "cargo-mobile"]
nextest = ["bin", "cargo-nextest"]
release = ["bin", "cargo-release"]
