on: [push, pull_request]

name: ci

jobs:
  build_and_test:
    name: cargo-run-bin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1

      - name: Install deps
        run: |
          which cargo-cmd || cargo install cargo-cmd
          cargo cmd setup-nightly
          cargo install cargo-run-bin --target-dir ./target
          cargo bin --build
      - name: Lint
        run: cargo cmd lint
      - name: Test
        run: cargo cmd test-coverage-lcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
